name: Curry
on:
  push:
    branches:
      - feature/curry

jobs:
  example:
    runs-on: ubuntu-20.04
    name: env
    steps:
      - name: echo env
        run: echo ${STAGE}
        env:
          STAGE: staging
