name: Curry
on:
  push:
    branches:
      - feature/curry

jobs:
  example:
    runs-on: ubuntu-20.04
    name: env
    steps:
      - name: echo env
        run: echo ${STAGE}
        env:
          STAGE: staging
  example-2:
    runs-on: ubuntu-18.04
    name: public-env
    env:
      DAY_OF_WEEK: Mon
    steps:
      - name: "Hello world when it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Mon' }}
        run: |-
          echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday"
          echo "DAY_OF_WEEK $DAY_OF_WEEK"
          expr 1 + 1 > output.log
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
      - uses: actions/checkout@v2
      - name: "Ls"
        run: "ls -tlr"
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
